### ISSUE TITLE
[Bug]: KeyError: 'reward'

### ISSUE THREAD

**Issue by wcowboy** [OpenRL-Lab/openrl#24]
### 🐛 Bug

 base_reward.py中 rewards = data["reward"].copy()，没有reward，reward_wrapper.py是rewards，修改之后还有其他问题。。。
![image](https://user-images.githubusercontent.com/32413551/236144746-5b80d087-9203-4ec3-9c77-77045e5aee53.png)
![image](https://user-images.githubusercontent.com/32413551/236144960-65314b4e-b730-476b-a120-8022ee9091fe.png)

### To Reproduce

```python
# train_ppo.py
from openrl.envs.common import make
from openrl.modules.common import PPONet as Net
from openrl.runners.common import PPOAgent as Agent

env = make("CartPole-v1", env_num=9) # 创建环境，并设置环境并行数为9
net = Net(env) # 创建神经网络
agent = Agent(net) # 初始化训练器
agent.train(total_time_steps=20000) # 开始训练，并设置环境运行总步数为20000

```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/home/user/code/python/train_ppo.py", line 9, in <module>
    agent.train(total_time_steps=20000) # 开始训练，并设置环境运行总步数为20000
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/runners/common/ppo_agent.py", line 134, in train
    driver.run()
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/drivers/onpolicy_driver.py", line 227, in run
    self._inner_loop()
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/drivers/onpolicy_driver.py", line 112, in _inner_loop
    rollout_infos = self.actor_rollout()
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/drivers/onpolicy_driver.py", line 189, in actor_rollout
    obs, rewards, dones, infos = self.envs.step(actions, extra_data)
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/envs/vec_env/wrappers/vec_monitor_wrapper.py", line 37, in step
    returns = self.env.step(action, extra_data)
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/envs/vec_env/wrappers/reward_wrapper.py", line 46, in step
    rewards, new_infos = self.reward_class.step_reward(data=extra_data)
  File "/home/user/anaconda3/envs/OpenRL/lib/python3.9/site-packages/openrl/rewards/base_reward.py", line 18, in step_reward
    rewards = data["reward"].copy()
KeyError: 'reward'
```

### Checklist

- [X] I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
- [X] I have read the [documentation](https://openrl-docs.readthedocs.io/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have version numbers, operating system and environment, where applicable

**Comment by FIWE2030** [comment]
感觉还是有这个问题
