### ISSUE TITLE
[Bug]: incorrect key “reward” of data in base_reward.py:L15

### ISSUE THREAD

**Issue by han-x** [OpenRL-Lab/openrl#28]
### 🐛 Bug

It should be "rewards" instead of "reward".
`
    def step_reward(
        self, data: Dict[str, Any]
    ) -> Union[np.ndarray, List[Dict[str, Any]]]:
        print(data.keys())
        rewards = data["reward"].copy()
        infos = []
`
dict_keys(['values', 'action_log_probs', 'step', 'buffer', 'actions', 'obs', 'rewards', 'dones', 'infos'])

### To Reproduce

```python
from openrl import ...

```

### Relevant log output / Error message

```shell
Traceback (most recent call last):
  File "/data/workspace/openrl/examples/cartpole/train_ppo.py", line 39, in <module>
    agent = train()
  File "/data/workspace/openrl/examples/cartpole/train_ppo.py", line 17, in train
    agent.train(total_time_steps=20000)
  File "/data/workspace/openrl/openrl/runners/common/ppo_agent.py", line 134, in train
    driver.run()
  File "/data/workspace/openrl/openrl/drivers/onpolicy_driver.py", line 227, in run
    self._inner_loop()
  File "/data/workspace/openrl/openrl/drivers/onpolicy_driver.py", line 112, in _inner_loop
    rollout_infos = self.actor_rollout()
  File "/data/workspace/openrl/openrl/drivers/onpolicy_driver.py", line 189, in actor_rollout
    obs, rewards, dones, infos = self.envs.step(actions, extra_data)
  File "/data/workspace/openrl/openrl/envs/vec_env/wrappers/vec_monitor_wrapper.py", line 37, in step
    returns = self.env.step(action, extra_data)
  File "/data/workspace/openrl/openrl/envs/vec_env/wrappers/reward_wrapper.py", line 46, in step
    rewards, new_infos = self.reward_class.step_reward(data=extra_data)
  File "/data/workspace/openrl/openrl/rewards/base_reward.py", line 16, in step_reward
    rewards = data["reward"].copy()
KeyError: 'reward'
```

### Checklist

- [X] I have checked that there is no similar [issues](https://github.com/OpenRL-Lab/openrl/issues) in the repo
- [X] I have read the [documentation](https://openrl-docs.readthedocs.io/)
- [X] I have provided a minimal working example to reproduce the bug
- [X] I have version numbers, operating system and environment, where applicable

**Comment by huangshiyu13** [comment]
#29
